# mapping of speech input to symbols
symbol_mapping = {
            "semicolon": ";",
            "period": ".",
            "comma": ",",
            "colon": ":",
            "left parenthesis": "(",
            "right parenthesis": ")",
            "left angular":"<",
            "right angular":">",
            "left brace": "{",
            "right brace": "}",
            "left bracket": "[",
            "right bracket": "]",
            "single quotes": "' '",
            "double quotes": "\" \"",
            "Plus": "+",
            "minus": "-",
            "multiply": "*",
            "divide": "/",
            "modulus": "%",
            "not equals": "!=",
            "equals": "=",
            "greater than or equal to": ">=",
            "less than or equal to": "<=",
            "greater than": ">",
            "less than": "<",        
            "logical and": "&&",
            "logical or": "||",
            "logical not": "!",
            "dot" : ".",
            "next line" : "\n",
            "star" : "*"
        }